os: Visual Studio 2017

environment:
  node_pre_gyp_accessKeyId:
    secure: FJKFRMFNTu0HptoEfR1i4sAbIb4yoTFKbtdE/7OVEZ8=
  node_pre_gyp_secretAccessKey:
    secure: X1NwfNPq965IXFmgBd9TAm0kF7x9kdELhfhWcKslpPyuUWGJd51PIA5dhWCMn8ye
  matrix:
    - nodejs_version: 10
      platform: x64
      libtorch_url: https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-latest.zip

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - ps: Set-ExecutionPolicy Unrestricted -Scope CurrentUser -Force
  - ps: Invoke-WebRequest -Uri $env:libtorch_url -OutFile libtorch.zip
  - ps: Expand-Archive libtorch.zip -DestinationPath . -Force
  - npm config get
  - node --version
  - npm --version
  - node -e "console.log(process.arch);"
  - dir
  - IF /I "%PLATFORM%" == "x64" SET PATH=C:\Python27-x64;%PATH%
  - IF /I "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  - IF /I "%PLATFORM%" == "x64" CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd" -arch=x64
  - IF /I "%PLATFORM%" == "x86" CALL "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\vsdevcmd" -arch=x86
  - npm i --ignore-scripts
  - npm run pre-build
  - npm test
  - npm run pre-unpublish
  - npm run pre-publish

build: off
test: off
deploy: off